var herc_basis = new Image(); herc_basis.src = "ships/herc01/basis.png";
var herc_wings = new Image(); herc_wings.src = "ships/herc01/wings1.png";
var herc_pulse = new Image(); herc_pulse.src = "ships/herc01/pulse2.png";
var closestars = new Image(); closestars.src = "background/closestars.png";
var closestars1 = new Image(); closestars1.src = "background/closestars1.png";
var planet1 = new Image(); planet1.src = "background/Planet1.png";
var mercury = new Image(); mercury.src = "background/mercury.png";
var venus = new Image(); venus.src = "background/venus4.png";
var earth = new Image(); earth.src = "background/terra.png";
var mars = new Image(); mars.src = "background/mars.png";
var glowr = new Image(); glowr.src = "background/HaloRed.png";
var glowo = new Image(); glowo.src = "background/HaloOrange.png";
var glowy = new Image(); glowy.src = "background/HaloYellow.png";
var glowb = new Image(); glowb.src = "background/HaloBlue.png";
var gloww = new Image(); gloww.src = "background/HaloWhite.png";
var gloww2 = new Image(); gloww2.src = "background/HaloWhite2.png";
var star1 = new Image(); star1.src = "background/Star1.png";
var star2 = new Image(); star2.src = "background/Star2.png";
var star3 = new Image(); star3.src = "background/Star3.png";
var star4 = new Image(); star4.src = "background/Star4.png";
var star5 = new Image(); star5.src = "background/Star5.png";
var star6 = new Image(); star6.src = "background/Star6.png";
var star7 = new Image(); star7.src = "background/Star7.png";
var star8 = new Image(); star8.src = "background/Star8.png";
var star9 = new Image(); star9.src = "background/Star9.png";
var star10 = new Image(); star10.src = "background/Star10.png";
var star11 = new Image(); star11.src = "background/Star11.png";
var rock1 = new Image(); rock1.src = "debree/rock1.png";
var rock2 = new Image(); rock2.src = "debree/rock2.png";
var rock3 = new Image(); rock3.src = "debree/rock3.png";
var herc_fire1_1 = new Image(); herc_fire1_1.src = "ships/herc01/fire1_1.png";var herc_fire1_2 = new Image(); herc_fire1_2.src = "ships/herc01/fire1_2.png";var herc_fire1_3 = new Image(); herc_fire1_3.src = "ships/herc01/fire1_3.png";
var herc_fire0_1 = new Image(); herc_fire0_1.src = "ships/herc01/fire0_1.png";var herc_fire0_2 = new Image(); herc_fire0_2.src = "ships/herc01/fire0_2.png";var herc_fire0_3 = new Image(); herc_fire0_3.src = "ships/herc01/fire0_3.png";
var herc_fire2_1 = new Image(); herc_fire2_1.src = "ships/herc01/fire2_1.png";var herc_fire2_2 = new Image(); herc_fire2_2.src = "ships/herc01/fire2_2.png";var herc_fire2_3 = new Image(); herc_fire2_3.src = "ships/herc01/fire2_3.png";
var herc_fire3_1 = new Image(); herc_fire3_1.src = "ships/herc01/fire3_1.png";var herc_fire3_2 = new Image(); herc_fire3_2.src = "ships/herc01/fire3_2.png";var herc_fire3_3 = new Image(); herc_fire3_3.src = "ships/herc01/fire3_3.png";
var herc_fire4_1 = new Image(); herc_fire4_1.src = "ships/herc01/fire4_1.png";var herc_fire4_2 = new Image(); herc_fire4_2.src = "ships/herc01/fire4_2.png";var herc_fire4_3 = new Image(); herc_fire4_3.src = "ships/herc01/fire4_3.png";
var herc_fire5_1 = new Image(); herc_fire5_1.src = "ships/herc01/fire5_1.png";var herc_fire5_2 = new Image(); herc_fire5_2.src = "ships/herc01/fire5_2.png";var herc_fire5_3 = new Image(); herc_fire5_3.src = "ships/herc01/fire5_3.png";


var tunnel = new Image(); tunnel.src = "background/tunnelvision.png";
var blur1 = new Image(); blur1.src = "ships/speed0_1.png";
var blur2 = new Image(); blur2.src = "ships/speed0_2.png";
var blur3 = new Image(); blur3.src = "ships/speed0_3.png";
var blur4 = new Image(); blur4.src = "ships/speed0_4.png";
var blur5 = new Image(); blur5.src = "ships/speed0_5.png";
var blur6 = new Image(); blur6.src = "ships/speed0_6.png";
var blur7 = new Image(); blur7.src = "ships/speed1_1.png";
var blur8 = new Image(); blur8.src = "ships/speed1_2.png";
var blur9 = new Image(); blur9.src = "ships/speed1_3.png";
var blur10 = new Image(); blur10.src = "ships/speed1_4.png";
var blur11 = new Image(); blur11.src = "ships/speed1_5.png";
var blur12 = new Image(); blur12.src = "ships/speed1_6.png";
var blur13 = new Image(); blur13.src = "ships/speed2_1.png";
var blur14 = new Image(); blur14.src = "ships/speed2_2.png";
var blur15 = new Image(); blur15.src = "ships/speed2_3.png";
var blur16 = new Image(); blur16.src = "ships/speed2_4.png";
var blur17 = new Image(); blur17.src = "ships/speed2_5.png";
var blur18 = new Image(); blur18.src = "ships/speed2_6.png";